# Parse PAF file to get rough mapping of GRCh38 unmapped contigs to T2T-CHM13

* Get info on unmapped contig: length and asserted chromosome assignment if it exists
* Parse alignmnets and generate stats, look for inconsistencies, etc.

In [24]:
import csv
import pandas as pd
import jsonlines
import numpy as np

In [25]:
# read in seq report file
grch38_primary_df=pd.read_csv("../../genome_data/GRCh38/GCF_000001405.40/sequence_report.tsv", sep="\t", header=0, usecols=['Chromosome name', 'RefSeq seq accession', 'Role', 'Seq length', 'UCSC style name'])
display(grch38_primary_df)

,Chromosome name,RefSeq seq accession,Role,Seq length,UCSC style name
0,1,NC_000001.11,assembled-molecule,248956422,chr1
1,2,NC_000002.12,assembled-molecule,242193529,chr2
2,3,NC_000003.12,assembled-molecule,198295559,chr3
3,4,NC_000004.12,assembled-molecule,190214555,chr4
4,5,NC_000005.10,assembled-molecule,181538259,chr5
...,...,...,...,...,...
186,Un,NT_187509.1,unplaced-scaffold,40191,chrUn_KI270754v1
187,Un,NT_187510.1,unplaced-scaffold,36723,chrUn_KI270755v1
188,Un,NT_187511.1,unplaced-scaffold,79590,chrUn_KI270756v1
189,Un,NT_187512.1,unplaced-scaffold,71251,chrUn_KI270757v1
190,MT,NC_012920.1,assembled-molecule,16569,chrM

In [26]:
# get rid of 'assembled-molecules'
unmap_df=grch38_primary_df.loc[grch38_primary_df['Role'] != 'assembled-molecule']
display(unmap_df)

,Chromosome name,RefSeq seq accession,Role,Seq length,UCSC style name
24,1,NT_187361.1,unlocalized-scaffold,175055,chr1_KI270706v1_random
25,1,NT_187362.1,unlocalized-scaffold,32032,chr1_KI270707v1_random
26,1,NT_187363.1,unlocalized-scaffold,127682,chr1_KI270708v1_random
27,1,NT_187364.1,unlocalized-scaffold,66860,chr1_KI270709v1_random
28,1,NT_187365.1,unlocalized-scaffold,40176,chr1_KI270710v1_random
...,...,...,...,...,...
185,Un,NT_187508.1,unplaced-scaffold,62944,chrUn_KI270753v1
186,Un,NT_187509.1,unplaced-scaffold,40191,chrUn_KI270754v1
187,Un,NT_187510.1,unplaced-scaffold,36723,chrUn_KI270755v1
188,Un,NT_187511.1,unplaced-scaffold,79590,chrUn_KI270756v1
189,Un,NT_187512.1,unplaced-scaffold,71251,chrUn_KI270757v1

In [27]:
grc_unmap_chr=dict(zip(unmap_df['RefSeq seq accession'], unmap_df['Chromosome name']))
print(grc_unmap_chr)

{'NT_187361.1': '1', 'NT_187362.1': '1', 'NT_187363.1': '1', 'NT_187364.1': '1', 'NT_187365.1': '1', 'NT_187366.1': '1', 'NT_187367.1': '1', 'NT_187368.1': '1', 'NT_187369.1': '1', 'NT_187370.1': '2', 'NT_187371.1': '2', 'NT_167215.1': '3', 'NT_113793.3': '4', 'NT_113948.1': '5', 'NT_187372.1': '9', 'NT_187373.1': '9', 'NT_187374.1': '9', 'NT_187375.1': '9', 'NT_113796.3': '14', 'NT_113888.1': '14', 'NT_167219.1': '14', 'NT_187377.1': '14', 'NT_187378.1': '14', 'NT_187379.1': '14', 'NT_187380.1': '14', 'NT_187381.1': '14', 'NT_187382.1': '15', 'NT_187383.1': '16', 'NT_113930.2': '17', 'NT_187384.1': '17', 'NT_187385.1': '17', 'NT_187386.1': '22', 'NT_187387.1': '22', 'NT_187388.1': '22', 'NT_187390.1': '22', 'NT_187391.1': '22', 'NT_187392.1': '22', 'NT_187393.1': '22', 'NT_187394.1': '22', 'NT_187395.1': 'Y', 'NT_113901.1': 'Un', 'NT_167208.1': 'Un', 'NT_167209.1': 'Un', 'NT_167211.2': 'Un', 'NT_113889.1': 'Un', 'NT_167213.1': 'Un', 'NT_167214.1': 'Un', 'NT_167218.1': 'Un', 'NT_167220.1': 'Un', 'NT_187396.1': 'Un', 'NT_187398.1': 'Un', 'NT_187397.1': 'Un', 'NT_187399.1': 'Un', 'NT_187402.1': 'Un', 'NT_187406.1': 'Un', 'NT_187405.1': 'Un', 'NT_187404.1': 'Un', 'NT_187403.1': 'Un', 'NT_187407.1': 'Un', 'NT_187401.1': 'Un', 'NT_187400.1': 'Un', 'NT_187459.1': 'Un', 'NT_187458.1': 'Un', 'NT_187461.1': 'Un', 'NT_187460.1': 'Un', 'NT_187462.1': 'Un', 'NT_187465.1': 'Un', 'NT_187466.1': 'Un', 'NT_187463.1': 'Un', 'NT_187464.1': 'Un', 'NT_187469.1': 'Un', 'NT_187467.1': 'Un', 'NT_187468.1': 'Un', 'NT_187470.1': 'Un', 'NT_187494.1': 'Un', 'NT_187491.1': 'Un', 'NT_187492.1': 'Un', 'NT_187490.1': 'Un', 'NT_187493.1': 'Un', 'NT_187489.1': 'Un', 'NT_187471.1': 'Un', 'NT_187472.1': 'Un', 'NT_187486.1': 'Un', 'NT_187488.1': 'Un', 'NT_187482.1': 'Un', 'NT_187484.1': 'Un', 'NT_187487.1': 'Un', 'NT_187480.1': 'Un', 'NT_187475.1': 'Un', 'NT_187478.1': 'Un', 'NT_187473.1': 'Un', 'NT_187474.1': 'Un', 'NT_187481.1': 'Un', 'NT_187485.1': 'Un', 'NT_187483.1': 'Un', 'NT_187479.1': 'Un', 'NT_187476.1': 'Un', 'NT_187477.1': 'Un', 'NT_187409.1': 'Un', 'NT_187408.1': 'Un', 'NT_187410.1': 'Un', 'NT_187415.1': 'Un', 'NT_187412.1': 'Un', 'NT_187411.1': 'Un', 'NT_187413.1': 'Un', 'NT_187416.1': 'Un', 'NT_187417.1': 'Un', 'NT_187414.1': 'Un', 'NT_187418.1': 'Un', 'NT_187419.1': 'Un', 'NT_187424.1': 'Un', 'NT_187425.1': 'Un', 'NT_187420.1': 'Un', 'NT_187495.1': 'Un', 'NT_187422.1': 'Un', 'NT_187421.1': 'Un', 'NT_187423.1': 'Un', 'NT_187426.1': 'Un', 'NT_187437.1': 'Un', 'NT_187430.1': 'Un', 'NT_187428.1': 'Un', 'NT_187427.1': 'Un', 'NT_187435.1': 'Un', 'NT_187432.1': 'Un', 'NT_187436.1': 'Un', 'NT_187431.1': 'Un', 'NT_187438.1': 'Un', 'NT_187429.1': 'Un', 'NT_187433.1': 'Un', 'NT_187496.1': 'Un', 'NT_187434.1': 'Un', 'NT_187440.1': 'Un', 'NT_187439.1': 'Un', 'NT_187441.1': 'Un', 'NT_187443.1': 'Un', 'NT_187442.1': 'Un', 'NT_187444.1': 'Un', 'NT_187445.1': 'Un', 'NT_187450.1': 'Un', 'NT_187448.1': 'Un', 'NT_187449.1': 'Un', 'NT_187454.1': 'Un', 'NT_187446.1': 'Un', 'NT_187453.1': 'Un', 'NT_187447.1': 'Un', 'NT_187455.1': 'Un', 'NT_187451.1': 'Un', 'NT_187452.1': 'Un', 'NT_187457.1': 'Un', 'NT_187456.1': 'Un', 'NT_187497.1': 'Un', 'NT_187513.1': 'Un', 'NT_187498.1': 'Un', 'NT_187499.1': 'Un', 'NT_187500.1': 'Un', 'NT_187501.1': 'Un', 'NT_187502.1': 'Un', 'NT_187503.1': 'Un', 'NT_187504.1': 'Un', 'NT_187505.1': 'Un', 'NT_187506.1': 'Un', 'NT_187508.1': 'Un', 'NT_187509.1': 'Un', 'NT_187510.1': 'Un', 'NT_187511.1': 'Un', 'NT_187512.1': 'Un'}

In [29]:
#Get chromosome information for T2T-CHM13 to make things more readable.
T2T_acc2name={}
with jsonlines.open('../../genome_data/T2T-CHM13/GCF_009914755.1/sequence_report.jsonl') as reader:
    for obj in reader.iter(type=dict):
        acc=obj['refseqAccession']
        name=obj['chrName']
        T2T_acc2name[acc]=name
T2T_acc2name['NC_060948.1'] = 'Y'
print(T2T_acc2name)

{'NC_060925.1': '1', 'NC_060926.1': '2', 'NC_060927.1': '3', 'NC_060928.1': '4', 'NC_060929.1': '5', 'NC_060930.1': '6', 'NC_060931.1': '7', 'NC_060932.1': '8', 'NC_060933.1': '9', 'NC_060934.1': '10', 'NC_060935.1': '11', 'NC_060936.1': '12', 'NC_060937.1': '13', 'NC_060938.1': '14', 'NC_060939.1': '15', 'NC_060940.1': '16', 'NC_060941.1': '17', 'NC_060942.1': '18', 'NC_060943.1': '19', 'NC_060944.1': '20', 'NC_060945.1': '21', 'NC_060946.1': '22', 'NC_060947.1': 'X', 'NC_060948.1': 'Y'}

In [30]:
align_df=pd.read_csv("../results/GRCh38_unmap2T2T-CHM13.paf", sep="\t", header=None, usecols=[0,1,2,3,4,5,6,7,8,9,10,11, 12], names=['GRCh38_contig', 
'GRCh38_contig_len', 'GRCh38_contig_start', 'GRCh38_contig_end', 'strand', 'T2T_seq', 'T2T_seq_len', 'T2T_start', 'T2T_end', 'MatchBases', 'NumBasesInMap', 'MapQuality', 'Alignment'])
display(align_df)

,GRCh38_contig,GRCh38_contig_len,GRCh38_contig_start,GRCh38_contig_end,strand,T2T_seq,T2T_seq_len,T2T_start,T2T_end,MatchBases,NumBasesInMap,MapQuality,Alignment
0,NT_187361.1,175055,9,175052,-,NC_060925.1,248387328,127758003,127933030,162953,175070,60,tp:A:P
1,NT_187361.1,175055,9,175052,+,NC_060945.1,45090682,7469257,7640947,132424,179433,0,tp:A:S
2,NT_187361.1,175055,9,175052,+,NC_060946.1,51324926,10501947,10673676,132214,179419,0,tp:A:S
3,NT_187361.1,175055,9,175052,+,NC_060938.1,101161492,5671871,5843509,132143,179338,0,tp:A:S
4,NT_187362.1,32032,3,32023,-,NC_060925.1,248387328,127727977,127759997,27861,32020,48,tp:A:P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,NT_167211.2,176608,6832,8824,+,NC_060938.1,101161492,4747650,4749668,76,2052,17,tp:A:P
579,NT_167211.2,176608,646,1058,+,NC_060938.1,101161492,4893208,4893625,48,422,3,tp:A:P
580,NT_113889.1,161147,1,161146,+,NC_060939.1,99753195,4778404,4939555,150446,161159,0,tp:A:P
581,NT_113889.1,161147,1,161146,+,NC_060937.1,113566686,9418929,9580062,150214,161155,0,tp:A:S
582,NT_113889.1,161147,1,161146,+,NC_060938.1,101161492,2890242,3054840,138714,164777,0,tp:A:S

In [31]:
#Add T2T chromosome name to dataframe
align_df.insert(6, 'chr_name', (align_df['T2T_seq'].map(T2T_acc2name)))
align_df.insert(1, 'grc_chr_name', (align_df['GRCh38_contig'].map(grc_unmap_chr)))
align_df.insert(5, 'align_cov', ((align_df['GRCh38_contig_end'] - align_df['GRCh38_contig_start'])/align_df['GRCh38_contig_len']))
display(align_df)

,GRCh38_contig,grc_chr_name,GRCh38_contig_len,GRCh38_contig_start,GRCh38_contig_end,align_cov,strand,T2T_seq,chr_name,T2T_seq_len,T2T_start,T2T_end,MatchBases,NumBasesInMap,MapQuality,Alignment
0,NT_187361.1,1,175055,9,175052,0.999931,-,NC_060925.1,1,248387328,127758003,127933030,162953,175070,60,tp:A:P
1,NT_187361.1,1,175055,9,175052,0.999931,+,NC_060945.1,21,45090682,7469257,7640947,132424,179433,0,tp:A:S
2,NT_187361.1,1,175055,9,175052,0.999931,+,NC_060946.1,22,51324926,10501947,10673676,132214,179419,0,tp:A:S
3,NT_187361.1,1,175055,9,175052,0.999931,+,NC_060938.1,14,101161492,5671871,5843509,132143,179338,0,tp:A:S
4,NT_187362.1,1,32032,3,32023,0.999625,-,NC_060925.1,1,248387328,127727977,127759997,27861,32020,48,tp:A:P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,NT_167211.2,Un,176608,6832,8824,0.011279,+,NC_060938.1,14,101161492,4747650,4749668,76,2052,17,tp:A:P
579,NT_167211.2,Un,176608,646,1058,0.002333,+,NC_060938.1,14,101161492,4893208,4893625,48,422,3,tp:A:P
580,NT_113889.1,Un,161147,1,161146,0.999988,+,NC_060939.1,15,99753195,4778404,4939555,150446,161159,0,tp:A:P
581,NT_113889.1,Un,161147,1,161146,0.999988,+,NC_060937.1,13,113566686,9418929,9580062,150214,161155,0,tp:A:S
582,NT_113889.1,Un,161147,1,161146,0.999988,+,NC_060938.1,14,101161492,2890242,3054840,138714,164777,0,tp:A:S

In [32]:
#Make a dataframe that just has primary alignments
prim_df = align_df[align_df['Alignment'] == 'tp:A:P']
display(prim_df)

,GRCh38_contig,grc_chr_name,GRCh38_contig_len,GRCh38_contig_start,GRCh38_contig_end,align_cov,strand,T2T_seq,chr_name,T2T_seq_len,T2T_start,T2T_end,MatchBases,NumBasesInMap,MapQuality,Alignment
0,NT_187361.1,1,175055,9,175052,0.999931,-,NC_060925.1,1,248387328,127758003,127933030,162953,175070,60,tp:A:P
4,NT_187362.1,1,32032,3,32023,0.999625,-,NC_060925.1,1,248387328,127727977,127759997,27861,32020,48,tp:A:P
8,NT_187363.1,1,127682,74,127675,0.999366,-,NC_060938.1,14,101161492,4493608,4623419,99502,131205,60,tp:A:P
14,NT_187364.1,1,66860,17663,66852,0.735701,+,NC_060925.1,1,248387328,128780915,128830089,45393,49194,0,tp:A:P
16,NT_187364.1,1,66860,173,17532,0.259632,-,NC_060925.1,1,248387328,129609275,129628840,3464,19759,0,tp:A:P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,NT_167211.2,Un,176608,8180,12335,0.023527,+,NC_060941.1,17,84276897,22235872,22240092,114,4251,20,tp:A:P
577,NT_167211.2,Un,176608,10024,27380,0.098274,-,NC_060944.1,20,66210255,32587390,32604893,126,17560,14,tp:A:P
578,NT_167211.2,Un,176608,6832,8824,0.011279,+,NC_060938.1,14,101161492,4747650,4749668,76,2052,17,tp:A:P
579,NT_167211.2,Un,176608,646,1058,0.002333,+,NC_060938.1,14,101161492,4893208,4893625,48,422,3,tp:A:P
580,NT_113889.1,Un,161147,1,161146,0.999988,+,NC_060939.1,15,99753195,4778404,4939555,150446,161159,0,tp:A:P

In [36]:
##Got through each unamp contig to get information (how many primary alignments, secondary, etc.)
good_map_df = pd.DataFrame()
review_map_df = pd.DataFrame()
for seq in grc_unmap_chr:
    temp_df=prim_df.loc[align_df['GRCh38_contig'] == seq]
    if (len(temp_df) == 1):
        #print(type(prim_df.loc[0]['align_cov']))
        if abs(prim_df.loc[0]['align_cov']) > 0.99:
            good_map_df = pd.concat([good_map_df, temp_df])
        else:
            review_map_df = pd.concat([review_map_df, temp_df])
    else:
        review_map_df = pd.concat([review_map_df, temp_df])

print("Good Map Contigs: %d" % len(good_map_df))
print("Review contigs: %d" % (len(grc_unmap_chr) - len(good_map_df)))
display(good_map_df)
display(review_map_df)

Good Map Contigs: 132
Review contigs: 34

,GRCh38_contig,grc_chr_name,GRCh38_contig_len,GRCh38_contig_start,GRCh38_contig_end,align_cov,strand,T2T_seq,chr_name,T2T_seq_len,T2T_start,T2T_end,MatchBases,NumBasesInMap,MapQuality,Alignment
0,NT_187361.1,1,175055,9,175052,0.999931,-,NC_060925.1,1,248387328,127758003,127933030,162953,175070,60,tp:A:P
4,NT_187362.1,1,32032,3,32023,0.999625,-,NC_060925.1,1,248387328,127727977,127759997,27861,32020,48,tp:A:P
8,NT_187363.1,1,127682,74,127675,0.999366,-,NC_060938.1,14,101161492,4493608,4623419,99502,131205,60,tp:A:P
18,NT_187365.1,1,40176,1,40170,0.999826,+,NC_060938.1,14,101161492,4621493,4661792,31568,40338,34,tp:A:P
24,NT_187366.1,1,42210,13,42205,0.999574,-,NC_060925.1,1,248387328,16612050,16660528,37827,48538,12,tp:A:P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,NT_187508.1,Un,62944,3,62937,0.999841,+,NC_060938.1,14,101161492,7077511,7141111,61288,63607,15,tp:A:P
542,NT_187509.1,Un,40191,10,40186,0.999627,+,NC_060937.1,13,113566686,12289026,12333524,33396,44517,0,tp:A:P
548,NT_187510.1,Un,36723,8,36717,0.999619,-,NC_060928.1,4,193574945,193028634,193063957,32716,36987,60,tp:A:P
551,NT_187511.1,Un,79590,1,79567,0.999698,-,NC_060934.1,10,134758134,38897308,38976937,59079,79714,60,tp:A:P
552,NT_187512.1,Un,71251,5,71245,0.999846,-,NC_060939.1,15,99753195,14202009,14267715,42750,73505,60,tp:A:P

,GRCh38_contig,grc_chr_name,GRCh38_contig_len,GRCh38_contig_start,GRCh38_contig_end,align_cov,strand,T2T_seq,chr_name,T2T_seq_len,T2T_start,T2T_end,MatchBases,NumBasesInMap,MapQuality,Alignment
14,NT_187364.1,1,66860,17663,66852,0.735701,+,NC_060925.1,1,248387328,128780915,128830089,45393,49194,0,tp:A:P
16,NT_187364.1,1,66860,173,17532,0.259632,-,NC_060925.1,1,248387328,129609275,129628840,3464,19759,0,tp:A:P
17,NT_187364.1,1,66860,15672,19646,0.059438,+,NC_060925.1,1,248387328,127088321,127092118,453,3977,60,tp:A:P
34,NT_187369.1,1,41717,9899,41708,0.762495,+,NC_060925.1,1,248387328,16396444,16431425,27626,35060,60,tp:A:P
35,NT_187369.1,1,41717,37,9887,0.236115,-,NC_060925.1,1,248387328,145169232,145179102,7452,9906,46,tp:A:P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,NT_187500.1,Un,41891,29613,41890,0.293070,+,NC_060933.1,9,150617247,150596809,150609086,12025,12277,19,tp:A:P
515,NT_187501.1,Un,66486,21802,66479,0.671976,+,NC_060938.1,14,101161492,3480844,3525515,39813,44708,0,tp:A:P
520,NT_187501.1,Un,66486,2,21794,0.327768,+,NC_060946.1,22,51324926,6429997,6451788,20944,21792,60,tp:A:P
521,NT_187502.1,Un,198735,6,197306,0.992779,+,NC_060933.1,9,150617247,44854409,45049035,96073,209657,60,tp:A:P
527,NT_187502.1,Un,198735,196176,198650,0.012449,+,NC_060933.1,9,150617247,45024966,45027445,286,2479,31,tp:A:P

In [37]:
# create bed
#'chr'chr_name\tT2T_start\tT2T_end\tGRCh38_contig_grc\tMapQuality\tstrand
good_map_bed_df=good_map_df[["chr_name", "T2T_start", "T2T_end", "GRCh38_contig", "MapQuality", "strand"]]
#good_map_bed_df['chr_name'] = 'chr' + good_map_bed_df['chr_name'].astype(str)
good_map_bed_df['chr_name'] = good_map_bed_df['chr_name'].apply(lambda x: f"chr{x}")
display(good_map_bed_df)

/var/folders/nc/8xd1vn2n62dgdsxxm4vzqjtm0000gn/T/ipykernel_97073/812220686.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  good_map_bed_df['chr_name'] = good_map_bed_df['chr_name'].apply(lambda x: f"chr{x}")

    chr_name  T2T_start    T2T_end GRCh38_contig  MapQuality strand
0       chr1  127758003  127933030   NT_187361.1          60      -
4       chr1  127727977  127759997   NT_187362.1          48      -
8      chr14    4493608    4623419   NT_187363.1          60      -
18     chr14    4621493    4661792   NT_187365.1          34      +
24      chr1   16612050   16660528   NT_187366.1          12      -
..       ...        ...        ...           ...         ...    ...
539    chr14    7077511    7141111   NT_187508.1          15      +
542    chr13   12289026   12333524   NT_187509.1           0      +
548     chr4  193028634  193063957   NT_187510.1          60      -
551    chr10   38897308   38976937   NT_187511.1          60      -
552    chr15   14202009   14267715   NT_187512.1          60      -

[132 rows x 6 columns]

In [38]:
good_bed="../results/GRCh38_unmap2T2T-CHM13_from_paf_good_map.bed"
good_map_bed_df.to_csv(good_bed, sep="\t", index=False, header=False)

In [39]:
review_map_bed_df=review_map_df[["chr_name", "T2T_start", "T2T_end", "GRCh38_contig", "MapQuality", "strand"]]
review_map_bed_df['chr_name'] = review_map_bed_df['chr_name'].apply(lambda x: f"chr{x}")
display(review_map_bed_df)

/var/folders/nc/8xd1vn2n62dgdsxxm4vzqjtm0000gn/T/ipykernel_97073/2190188512.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_map_bed_df['chr_name'] = review_map_bed_df['chr_name'].apply(lambda x: f"chr{x}")

    chr_name  T2T_start    T2T_end GRCh38_contig  MapQuality strand
14      chr1  128780915  128830089   NT_187364.1           0      +
16      chr1  129609275  129628840   NT_187364.1           0      -
17      chr1  127088321  127092118   NT_187364.1          60      +
34      chr1   16396444   16431425   NT_187369.1          60      +
35      chr1  145169232  145179102   NT_187369.1          46      -
..       ...        ...        ...           ...         ...    ...
514     chr9  150596809  150609086   NT_187500.1          19      +
515    chr14    3480844    3525515   NT_187501.1           0      +
520    chr22    6429997    6451788   NT_187501.1          60      +
521     chr9   44854409   45049035   NT_187502.1          60      +
527     chr9   45024966   45027445   NT_187502.1          31      +

[116 rows x 6 columns]

In [40]:
review_bed="../results/GRCh38_unmap2T2T-CHM13_from_paf_review_map.bed"
review_map_bed_df.to_csv(review_bed, sep="\t", index=False, header=False)

In [ ]:
#make a list for quicker lookup (chr:start-stop)